apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-api-config
  namespace: rag-system
data:
  SERVICE_NAME: "ingestion-api"
  LOG_LEVEL: "INFO"
  PORT: "8082"

  # MinIO
  MINIO_ENDPOINT: "http://xrag-minio:9000"
  MINIO_BUCKET: "documents"
  MINIO_SECURE: "false"

  # Kafka
  KAFKA_BOOTSTRAP: "xrag-kafka:9092"
  KAFKA_TOPIC: "document-changes"
  KAFKA_ACKS: "1"

  # API
  MAX_CONTENT_LENGTH: "10485760"
  CORS_ENABLED: "true"
