"""Type stubs for gRPC client instrumentors."""

class GrpcInstrumentorClient:
    """Synchronous gRPC client instrumentor."""

    def __init__(self) -> None: ...
    def instrument(self) -> None: ...
    def uninstrument(self) -> None: ...

class GrpcAioInstrumentorClient:
    """Asynchronous gRPC client instrumentor."""

    def __init__(self) -> None: ...
    def instrument(self) -> None: ...
    def uninstrument(self) -> None: ...
