"""Type stubs for gRPC server instrumentors."""

class GrpcAioInstrumentorServer:
    """Asynchronous gRPC server instrumentor."""

    def __init__(self) -> None: ...
    def instrument(self) -> None: ...
    def uninstrument(self) -> None: ...
