kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: xrag-k8

# Configure containerd to use the local registry
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://xrag-k8-kind-registry:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."xrag-k8-kind-registry:5000"]
      endpoint = ["http://xrag-k8-kind-registry:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."xrag-k8-kind-registry:5000".tls]
      insecure_skip_verify = true

nodes:
  - role: control-plane
    extraPortMappings:
      # Search UI
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # Ingestion API
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP
      # Weaviate
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      # Grafana
      - containerPort: 30030
        hostPort: 3000
        protocol: TCP
      # Prometheus
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
      # Redis
      - containerPort: 30079
        hostPort: 6379
        protocol: TCP
      # Kafka
      - containerPort: 30092
        hostPort: 9092
        protocol: TCP
    extraMounts:
      - hostPath: ./data/storage
        containerPath: /var/local-path-provisioner

  - role: worker
    extraMounts:
      - hostPath: ./data/storage
        containerPath: /var/local-path-provisioner

  - role: worker
    extraMounts:
      - hostPath: ./data/storage
        containerPath: /var/local-path-provisioner
